set runtimepath=~/.config/vim,/usr/share/vim/vimfiles,/usr/share/vim/vim80,/usr/share/vim/vimfiles/after,~/${XDG_CONFIG_HOME}vim/after
set viminfo+=n~/.config/vim/viminfo
syntax on
set relativenumber
set number
filetype plugin indent on
set expandtab softtabstop=2 shiftwidth=2
autocmd Filetype java setlocal expandtab sts=4 sw=4
set nowrap
set encoding=utf-8
set fileencoding=utf-8
colorscheme ir_black
set pastetoggle=<F2>
" additional latexsuite stuff
" filetype plugin indent on
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
" verify next one is necessary
" set runtimepath=~/.config/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/.config/vim/after
