set runtimepath=~/.config/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/${XDG_CONFIG_HOME}vim/after
set viminfo+=n~/.config/vim/viminfo
set viewdir=$VIMDOTDIR/views
syntax on
set relativenumber
set number
filetype plugin indent on
set expandtab softtabstop=2 shiftwidth=2
autocmd Filetype java setlocal expandtab sts=4 sw=4 colorcolumn=81
autocmd Filetype c setlocal noexpandtab sts=8 sw=8 colorcolumn=81
autocmd Filetype cpp setlocal noexpandtab sts=8 sw=8 colorcolumn=81
autocmd Filetype tex setlocal colorcolumn=81 spelllang=en spell
autocmd Filetype dot setlocal noexpandtab sts=8 sw=8 colorcolumn=81 autoindent
autocmd Filetype python setlocal expandtab sts=4 sw=4 colorcolumn=81
autocmd Filetype json setlocal foldmethod=syntax
au BufRead,BufNewFile *.g4 set filetype=antlr4
autocmd Filetype antlr4 setlocal noexpandtab sts=8 sw=8 colorcolumn=81 autoindent
set nowrap
set encoding=utf-8
set fileencoding=utf-8
colorscheme ir_black
hi Folded ctermfg=Grey
set pastetoggle=<F2>
" additional latexsuite stuff
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
set title

"xml folding
augroup XML
  let g:xml_syntax_folding=1
  autocmd!
  autocmd FileType xml setlocal foldmethod=syntax foldlevelstart=999 foldminlines=0
augroup END

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red
match ExtraWhitespace /\s\+$/
"
