set runtimepath=~/.config/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,~/${XDG_CONFIG_HOME}vim/after
set viminfo+=n~/.config/vim/viminfo
syntax on
set relativenumber
set number
filetype plugin indent on
set expandtab softtabstop=2 shiftwidth=2
autocmd Filetype java setlocal expandtab sts=4 sw=4 colorcolumn=81
autocmd Filetype c setlocal noexpandtab sts=8 sw=8 colorcolumn=81
autocmd Filetype tex setlocal colorcolumn=81 spelllang=en spell
set nowrap
set encoding=utf-8
set fileencoding=utf-8
colorscheme ir_black
hi Folded ctermfg=Grey
set pastetoggle=<F2>
" additional latexsuite stuff
set grepprg=grep\ -nH\ $*
let g:tex_flavor = "latex"
set title
